<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.10.1 on win32)" generated="20220223 11:57:50.181" rpa="false" schemaversion="2">
<suite id="s1" name="TC9 Basic Auth" source="G:\Robot\APIAuto\RobotAuto\TC9_Basic_Auth.robot">
<test id="s1-t1" name="BasicAuth">
<kw name="Create List" library="BuiltIn">
<var>${User_pwd}</var>
<arg>ToolsQA</arg>
<arg>TestPassword</arg>
<doc>Returns a list containing given items.</doc>
<msg timestamp="20220223 11:57:50.749" level="INFO">${User_pwd} = ['ToolsQA', 'TestPassword']</msg>
<status status="PASS" starttime="20220223 11:57:50.749" endtime="20220223 11:57:50.749"/>
</kw>
<kw name="Create Session" library="RequestsLibrary">
<arg>basicauth</arg>
<arg>http://restapi.demoqa.com</arg>
<arg>auth=${User_pwd}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<msg timestamp="20220223 11:57:50.749" level="INFO">Creating Session using : alias=basicauth, url=http://restapi.demoqa.com, headers={},                     cookies={}, auth=&lt;requests.auth.HTTPBasicAuth object at 0x00000047866199C0&gt;, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20220223 11:57:50.749" endtime="20220223 11:57:50.753"/>
</kw>
<kw name="GET On Session" library="RequestsLibrary">
<var>${get_response}</var>
<arg>basicauth</arg>
<arg>/authentication</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<msg timestamp="20220223 11:57:51.065" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000478661A7D0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /authentication</msg>
<msg timestamp="20220223 11:57:51.269" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000004786619A20&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /authentication</msg>
<msg timestamp="20220223 11:57:51.670" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000478661AB00&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /authentication</msg>
<msg timestamp="20220223 11:57:51.802" level="FAIL">ConnectionError: HTTPConnectionPool(host='restapi.demoqa.com', port=80): Max retries exceeded with url: /authentication (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000478661AD40&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))</msg>
<status status="FAIL" starttime="20220223 11:57:50.753" endtime="20220223 11:57:51.802"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>${get_response.content}</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" starttime="20220223 11:57:51.806" endtime="20220223 11:57:51.806"/>
</kw>
<kw name="Should Be Equal As Strings" library="BuiltIn">
<arg>${get_response.status_code} 200</arg>
<doc>Fails if objects are unequal after converting them to strings.</doc>
<status status="NOT RUN" starttime="20220223 11:57:51.806" endtime="20220223 11:57:51.806"/>
</kw>
<status status="FAIL" starttime="20220223 11:57:50.745" endtime="20220223 11:57:51.806">ConnectionError: HTTPConnectionPool(host='restapi.demoqa.com', port=80): Max retries exceeded with url: /authentication (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000478661AD40&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))</status>
</test>
<status status="FAIL" starttime="20220223 11:57:50.185" endtime="20220223 11:57:51.810"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="TC9 Basic Auth">TC9 Basic Auth</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220223 11:57:51.065" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000478661A7D0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /authentication</msg>
<msg timestamp="20220223 11:57:51.269" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000004786619A20&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /authentication</msg>
<msg timestamp="20220223 11:57:51.670" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000000478661AB00&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /authentication</msg>
</errors>
</robot>
